gps:
  delta_threshold_s: 1.0 # max time distance to the two measurements for interpolation.
  min_status: 0 # minimum status for a GPS to be valid
  max_sigma_xy: 8 # max xy sigma

odo:
  delta_threshold_s: 1.0 # max time distance to the two measurements for interpolation.

aruco:
  delta_threshold_s: 0.05 # max time distance to associate aruco observations to a state (with a lidar time)
  sigma_alpha: 3 # sigma for an ARUCO measurement. sigma degrees in the three angle rotations
  sigma_xy: 0.05 # sigma for an ARUCO measurement. sigma meters for xy
  sigma_z: 0.1 # sigma for an ARUCO measurement. sigma degrees in the three angle rotations

# the scanmatcher is used for sequential scanmatching and to find registrations between non-consecutive pointclouds
scanmatcher:
  voxel_size: null # Number or null
  # find the closest points within this distance in ICP
  distance_threshold: 10.0

  filter_by_radius:
    max_radius: 35 #100
    min_radius: 0.5  #0.5 para no encontrarse con el robot

  filter_by_height:
    min_height: -1.0
    max_height: 50.0

  normals:
    maximum_neighbors: 300 #50
    radius_normals: 3 #0.5

loop_closing:
  step_index: 20

map_viewer:
  voxel_size: 0.2
  keyframe_sampling: 20

